/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mickey;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shwetank
 */
public class S3 extends javax.swing.JFrame {

    /**
     * Creates new form S3
     */
    public S3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("eTERNAL bOOK sHOP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 20, 500, 30);

        ta1.setBackground(new java.awt.Color(0, 0, 0));
        ta1.setForeground(new java.awt.Color(255, 255, 255));
        ta1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "ISBN/OCLC Number", "Author", "Language", "Genre", "Rating", "Price(in Rs.)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ta1.setColumnSelectionAllowed(true);
        ta1.setOpaque(false);
        ta1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        ta1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(ta1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 80, 890, 250);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Display Existing Records");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(70, 370, 250, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(420, 500, 200, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(770, 370, 100, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mickey/twilight-books-cover-1024x640.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 940, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel m1=(DefaultTableModel)ta1.getModel();
         try
            {
                Class.forName("java.sql.DriverManager");
               Connection c3= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sa","root","tiger");
               Statement st=(Statement) c3.createStatement();
               String qe="select * from books ;";
              ResultSet rs= st.executeQuery(qe);
              while(rs.next())
              {
                  String name=rs.getString("name");
                  String isbn=rs.getString("isbn");
                  String aut=rs.getString("author");
                  String lan=rs.getString("language");
                  String gen=rs.getString("genre");
                  String rat=rs.getString("rating");
                  String price=rs.getString("price");
                  m1.addRow (new Object[] {name, isbn, aut, lan, gen, rat, price});
              }
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        F2 t=new F2();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
        DefaultTableModel m=(DefaultTableModel)ta1.getModel();
        int r=m.getRowCount();
        if(r>0)
        {for(int i=0; i<r; i++)
            m.removeRow(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        // TODO add your handling code here:
        DefaultTableModel m1=(DefaultTableModel)ta1.getModel();
         try
            {
                Class.forName("java.sql.DriverManager");
               Connection c3= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sa","root","tiger");
               Statement st=(Statement) c3.createStatement();
               String qe="select * from books ;";
              ResultSet rs= st.executeQuery(qe);
              while(rs.next())
              {
                  String name=rs.getString("name");
                  String isbn=rs.getString("isbn");
                  String aut=rs.getString("author");
                  String lan=rs.getString("language");
                  String gen=rs.getString("genre");
                  String rat=rs.getString("rating");
                  String price=rs.getString("price");
                  m1.addRow (new Object[] {name, isbn, aut, lan, gen, rat, price});
              }
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }

    }//GEN-LAST:event_jButton2KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ta1;
    // End of variables declaration//GEN-END:variables
}
