/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mickey;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Shwetank
 */
public class S41 extends javax.swing.JFrame {

    /**
     * Creates new form S41
     */
    public S41() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        cb2 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cb3 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("eTERNAL bOOK sHOP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 610, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name of the copy sold");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 90, 200, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Price per Copy");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 144, 160, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Total Number of Copies Sold");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 210, 230, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Total Amount (with S.Tax)");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 260, 220, 30);

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1);
        t1.setBounds(420, 100, 200, 30);

        t2.setEditable(false);
        getContentPane().add(t2);
        t2.setBounds(460, 150, 160, 30);
        getContentPane().add(t3);
        t3.setBounds(460, 210, 160, 30);

        t4.setEditable(false);
        getContentPane().add(t4);
        t4.setBounds(460, 260, 160, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Rs.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(400, 150, 30, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Today's Date");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(90, 310, 120, 30);

        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(cb1);
        cb1.setBounds(280, 310, 56, 30);

        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        getContentPane().add(cb2);
        cb2.setBounds(390, 310, 100, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Rs.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(410, 270, 21, 20);

        cb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0000", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024" }));
        getContentPane().add(cb3);
        cb3.setBounds(540, 310, 80, 30);

        jButton1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jButton1.setText("CALCULATE AMOUNT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 400, 220, 40);

        jButton2.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jButton2.setText("GET PRICE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 400, 130, 40);

        jButton3.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jButton3.setText("ENTER INTO BALANCESHEET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(180, 450, 270, 50);

        jButton4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(440, 520, 180, 40);

        jButton5.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jButton5.setText("RESET");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(60, 520, 160, 40);

        jButton6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        jButton6.setText("MAIN PAGE");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(270, 520, 140, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mickey/love_quote-wallpaper-3840x2160.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 680, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
          S4 t=new S4();
        t.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String a=t3.getText();
        String b=t2.getText();
        if (b.isEmpty())
            JOptionPane.showMessageDialog(null,"Please get the price of the book.");
        else if (a.isEmpty())
            JOptionPane.showMessageDialog(null,"Please enter the number of the books.");
        else{
        int cp=Integer.parseInt(b);
        double pr=Double.parseDouble(a);
        double st= 0.10*(cp*pr);
        double ab=(cp*pr)+st;
        t4.setText(""+ab);}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String name,cp,pr,amt;
        name=t1.getText();
        cp=t3.getText();
        pr=t2.getText();
        amt=t4.getText();
        Object d1=cb1.getSelectedItem();
        Object d2=cb2.getSelectedIndex();
        Object d3=cb3.getSelectedItem();
        String date=d3+"-"+d2+"-"+d1;
        if(name.isEmpty())
            JOptionPane.showMessageDialog(null,"Please enter the Name.");
       else if(cp.isEmpty())
            JOptionPane.showMessageDialog(null,"Please enter the number of copies sold.");
       else if(pr.isEmpty())
            JOptionPane.showMessageDialog(null,"Please enter the price.");
       else if(amt.isEmpty())
            JOptionPane.showMessageDialog(null,"Please calculate the amount");
         else if(date==null)
        JOptionPane.showMessageDialog(null,"Please select a date");
        else
       {
           try{
               Class.forName("java.sql.DriverManager");
               Connection c2= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sa","root","tiger");
               Statement st=(Statement) c2.createStatement();
               String qe="insert into bill values('"+name+"','"+pr+"','"+cp+"','"+date+"','"+amt+"');";
               st.executeUpdate(qe);
             
           }
           catch (ClassNotFoundException | SQLException e)
           {
               JOptionPane.showMessageDialog(null, e.getMessage());
           }
           JOptionPane.showMessageDialog(null,"Details Entered!!");
       }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String name=t1.getText();
        if(name.isEmpty())
        {
            t2.setText("");
            t3.setText("");
            t4.setText("");
            cb1.setSelectedIndex(-1);
            cb2.setSelectedIndex(-1);
            cb3.setSelectedIndex(-1);
            JOptionPane.showMessageDialog(null,"please enter the name of the book.");
            
        }
        else
        {
            try
            {
                Class.forName("java.sql.DriverManager");
               Connection c3= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sa","root","tiger");
               Statement st=(Statement) c3.createStatement();
               String qu="select price from books where name = '"+name+"' ;";
              ResultSet rs= st.executeQuery(qu);
              if(rs.next())
              {
                String price=rs.getString("price");
                  t2.setText(price);
            
        }
              else{
                  JOptionPane.showMessageDialog(null,"Sorry! But the book you specified isn't available at the moment.");
                 t2.setText("");             }
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        
        t1.setText("");
        t2.setText("");
        t3.setText(""); 
        t4.setText("");
 cb1.setSelectedIndex(0);
 cb2.setSelectedIndex(0);
     cb3.setSelectedIndex(0);   
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        F2 y=new F2();
         y.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
            String name=t1.getText();
        if(name.isEmpty())
        {
            t2.setText("");
            t3.setText("");
            t4.setText("");
            cb1.setSelectedIndex(-1);
            cb2.setSelectedIndex(-1);
            cb3.setSelectedIndex(-1);
            JOptionPane.showMessageDialog(null,"please enter the name of the book.");
            
        }
        else
        {
            try
            {
                Class.forName("java.sql.DriverManager");
               Connection c3= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/sa","root","tiger");
               Statement st=(Statement) c3.createStatement();
               String qu="select price from books where name = '"+name+"' ;";
              ResultSet rs= st.executeQuery(qu);
              if(rs.next())
              {
                String price=rs.getString("price");
                  t2.setText(price);
            
        }
              else{
                  JOptionPane.showMessageDialog(null,"Sorry! But the book you specified isn't available at the moment.");
                           t2.setText("");  }
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }
    }//GEN-LAST:event_t1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S41.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S41.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S41.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S41.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S41().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JComboBox cb3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
}
